version: 2.1

jobs:
  build-and-test:
    working_directory: ~/SampleCode
    docker:
      - image: "cimg/openjdk:11.0"
    steps:
      - checkout
      - run: javac Source.java
      - run: java Source
      - run: javac Test.java
      - run: java -ea Test

workflows:
  version: 2
  workflow-name:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - master
            tags:
              ignore: /.*/
            pull-requests:
              types:
                - opened
                - synchronize
        
