version: 2.1

jobs:
  build:
    working_directory: ~/Trigger
    docker:
      - image: "cimg/openjdk:11.0"
    steps:
      - checkout
      - run: javac Source.java
      - run: java hh
  test:
    working_directory: ~/Trigger
    docker:
      - image: "cimg/openjdk:11.0"
    steps:
      - checkout
      - run: javac Test.java
      - run: java -ea Test

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
